### ISSUE TITLE
How to compress the image from the clipboard directly?

### ISSUE THREAD

**Issue by GivenCui** [alfredapp/tinypng-workflow#1]

**Comment by vitorgalvao** [comment]
You can’t compress the image directly from the clipboard, you have to first save it somewhere, then compress it, then send it to the clipboard again. But an image file is not the same as raw clipboard data. [This workflow](https://github.com/alfredapp/tinypng-workflow/files/10564116/Clipboard.Compress.alfredworkflow.zip) does what you ask. It relies on having the TinyPNG workflow installed and configured. I’m considering if the functionality should go into the main one.
